- name: Pull script post-install repo
  git:
    repo: "https://github.com/VivekSR602/post-install.git"
    dest: "{{ post_install_script_path }}"
    update: yes
    #version: master
  run_once: yes
  delegate_to: localhost

- name: Block execute scripts
  include_tasks: ./execute_script.yml
  loop: "{{ lookup('fileglob', '{}/{}/*'.format(post_install_script_path, 'windows' if post_install_os|lower == 'windows' else 'unix'), wantlist=True) | sort(case_sensitive=False) }}"
  loop_control:
    extended: yes